# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitem',
            old_name='booker_id',
            new_name='booking_id',
        ),
    ]
