# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20170916_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booker',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booker_id',
            new_name='booker',
        ),
        migrations.RenameField(
            model_name='bookingitem',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='bookingitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='venue_id',
            new_name='venue',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='item_id',
            new_name='item',
        ),
    ]
