# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20170916_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookers', to='page.User'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='page.Booker'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingItems', to='page.Booking'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingItems', to='page.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='page.Venue'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='page.Item'),
        ),
        migrations.AlterField(
            model_name='space',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='page.Item'),
        ),
    ]
